# Generated by Django 4.0.5 on 2022-07-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='uploads/'),
        ),
    ]
